"""Initial migration

Revision ID: 2ea97d00082f
Revises: 
Create Date: 2025-07-08 09:00:27.971715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea97d00082f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('frontend_url', sa.String(), nullable=False),
    sa.Column('backend_url', sa.String(), nullable=False),
    sa.Column('xss_enabled', sa.Boolean(), nullable=True),
    sa.Column('sql_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port', 'host', name='unique_port_host')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    
    # Seed data - Insert admin user (password: 'waf')
    op.execute("""
        INSERT INTO users (username, password_hash, is_admin) 
        VALUES ('admin', '$2b$12$pfjctCXt4Q5b.QKI2pHNFuvgfWAMAdpt0FnIwHlitGbgwt8pssfla', true)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sites')
    # ### end Alembic commands ###
