"""add vt_enabled to sites table

Revision ID: 3f4b8c9d2e1a
Revises: d71fdf48bfad
Create Date: 2025-07-08 11:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4b8c9d2e1a'
down_revision = 'd71fdf48bfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('vt_enabled', sa.Boolean(), nullable=True, default=False))
    # Set default value for existing records
    op.execute("UPDATE sites SET vt_enabled = false WHERE vt_enabled IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'vt_enabled')
    # ### end Alembic commands ###
