services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: waf
      POSTGRES_PASSWORD: waf
      POSTGRES_DB: waf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waf -d waf"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  waf:
    build: 
      context: .
      dockerfile: ./waf/Dockerfile
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    environment:
      - DATABASE_URL=postgresql+asyncpg://waf:waf@postgres:5432/waf
      - REDIS_URL=redis://redis:6379
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - DEBUG=true
      - POLL_INTERVAL=5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  mitmproxy:
    build:
      context: .
      dockerfile: ./waf/Dockerfile.mitm
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - DATABASE_URL=postgresql+asyncpg://waf:waf@postgres:5432/waf
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
    # <<< THE FINAL FIX IS HERE
    command: >
      mitmweb
      --web-host 0.0.0.0
      --web-port 8080
      --listen-port 8888
      --mode reverse:http://waf:8081
      --set keep_host_header=true 
      -s /app/mitmproxy.py
    depends_on:
      waf:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://waf:waf@postgres:5432/waf
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: