version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: waf-postgres
    environment:
      - POSTGRES_DB=waf
      - POSTGRES_USER=waf
      - POSTGRES_PASSWORD=waf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waf -d waf"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - waf-core-net
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: waf-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - waf-core-net
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: waf-api
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://waf:waf@postgres/waf
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - waf-core-net
    restart: unless-stopped

  waf:
    build:
      context: .
      dockerfile: ./waf/Dockerfile
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql+asyncpg://waf:waf@postgres/waf
      - REDIS_URL=redis://redis:6379
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - DEBUG=true
      - POLL_INTERVAL=5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - waf-core-net
      - dvwa-net
      - juiceshop-net
      - hr-system-net
    restart: unless-stopped

  mitmproxy:
    build:
      context: .
      dockerfile: ./waf/Dockerfile.mitm
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - DATABASE_URL=postgresql+asyncpg://waf:waf@postgres/waf
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
    command: >
      mitmweb
      --web-host 0.0.0.0
      --web-port 8080
      --listen-port 8888
      --mode reverse:http://waf:8081
      --set keep_host_header=true
      -s /app/mitmproxy.py
    depends_on:
      - waf
    networks:
      - waf-core-net
      - dvwa-net
      - juiceshop-net
      - hr-system-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  waf-core-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.99.1.0/24

  dvwa-net:
    external: true
    name: dvwa-net

  juiceshop-net:
    external: true
    name: juiceshop-net

  hr-system-net:
    external: true
    name: hr-system-net