version: "3.9"

services:
  juice_shop_app:
    image: bkimminich/juice-shop
    environment:
      - PORT=80          # 3000 yerine 80’den dinle
    # Host'a port yok; yalnızca iç ağ
    networks:
      juiceshop-net:
        aliases: ["juiceshop-internal"]  # WAF bu isimle ulaşacak
    restart: unless-stopped

networks:
  juiceshop-net:
    external: true
    name: juiceshop-net
